global using log4net;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.FileProviders;
global using Newtonsoft.Json;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using Tour_Planner_DB;
global using Tour_Planner_Model;
global using Tour_Planner_Business;